### ISSUE TITLE
Nav Bar

### ISSUE THREAD

**Issue by TrentonBitterli** [jacobpalin/JacobPalinPortfolio#1]
Heath says the Navbar needs to stick. Needs to be bigger and more room. Maybe have it fill up the left side of the screen not just the tiny corner.

**Comment by jacobpalin** [comment]
I made the navbar fill up the entire left side of the screen and instead of hovering over it to show a bigger navbar, I opted for icons that I think fit for each section I have and completely removed the hovering dropdown menu.
