### ISSUE TITLE
FONT

### ISSUE THREAD

**Issue by TrentonBitterli** [jacobpalin/JacobPalinPortfolio#2]
It would be better if you used a different font choice than Arial.

**Comment by jackpolifka** [comment]
Arial is generally a good font for readability, but I wonder if it is the default for a lot of websites. With your website, do you want to showcase your graphic skills, programming skills, or both? If graphic skills or both, using a different font could be an opportunity to further showcase these skills. What are your thoughts?

**Comment by jacobpalin** [comment]
I'm not very concerned about having a unique font for my website. As long as it's readable then I think it's fine. If I find a font later on that I think better suits my website then I will change to use that font instead.
